6TH

In [1]:
#Create a numpy array with all ones 
import numpy as np
a = np.ones((3,3))
print(a)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [2]:
#Generate random integers from 5 to 10 and arrange them into 3 * 5 numpy array.
import numpy as np
a = np.random.randint(5,10,15)
a = a.reshape(3,5)
print(a)

[[7 5 9 9 5]
 [5 5 9 9 5]
 [7 5 9 5 6]]


In [10]:
#Create 4 * 4 identity matrix using numpy function and find its mean value.
import numpy as np
a = np.identity(4)
print(a)
print(a.mean())

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
0.25


In [3]:
#Create 3 * 3 matrix and pad (fill) the borders with 0
import numpy as np
a = np.ones((3,3))
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
#Create a 5 * 6 array between 10 to 1000 such that the difference between the elements are 12 and they are only even numbers. Print the even rows and odd columns from the array.
import numpy as np

arr = np.arange(10, 1001, 12)
arr = arr[arr % 2 == 0]
arr = arr[:30].reshape(5, 6)

for i in range(0, 5, 2):
    for j in range(1, 6, 2):
        print(arr[i][j], end=" ")
    print()

22 46 70 
166 190 214 
310 334 358 


In [9]:
#Take user input for dimension of matrix and create the following pattern.
import numpy as np
x=int(input("Enter the dimension of matrix: "))
a = np.ones((x,x))
a[1::2,::2] = 0
a[::2,1::2] = 0
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
